
agent_name: lail_byol_multiset

agent:
  _target_: agents.multi_dataset.lail_byol.LailByolAgent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  lr_BYOL: ${lr_BYOL}
  feature_dim: ${feature_dim}
  hidden_dim: 1024
  critic_target_tau: 0.01
  num_expl_steps: 2000
  update_every_steps: 2
  stddev_schedule: ${stddev_schedule}
  stddev_clip: 0.3
  use_tb: ${use_tb}
  reward_d_coef: 2.0
  discriminator_lr: ${discriminator_lr}
  spectral_norm_bool: ${spectral_norm_bool}
  check_every_steps: ${check_every_steps}
  log_std_bounds: [-5, 2]
  GAN_loss: ${GAN_loss}
  stochastic_encoder: ${stochastic_encoder}
  train_encoder_w_critic: ${train_encoder_w_critic}
  CL_data_type: ${CL_data_type}
  from_dem: ${from_dem}
  add_aug_anchor_and_positive: false
  aug_type: ${aug_type}
  apply_aug: ${apply_aug}
  grayscale: ${grayscale}
  depth_flag: ${depth_flag}
  segm_flag: ${segm_flag}

